service: ldap-app
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  timeout: 10
functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true